version: "3.9"

services:
  redis:
    image: redis
    restart: always

  backend:
    restart: always
    build:
      context: .
    volumes:
      - ./media:/media
    ports:
      - '80:80'
    command: ['python3', './manage.py', 'runserver', '0.0.0.0:80']

  worker:
    restart: always
    build:
      context: .
    volumes:
      - ./media:/media
    command: [ 'celery', '-A', 'comment_service' , 'worker' , '-P' , 'gevent']