# Generated by Django 4.2.2 on 2023-07-17 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_comment_main_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachedfile',
            options={'verbose_name': 'Files attached to comment'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['timestamp'], name='core_commen_timesta_765c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user_creator'], name='core_commen_user_cr_f385d4_idx'),
        ),
        migrations.DeleteModel(
            name='UserCreator',
        ),
    ]
